parserOptions:
  ecmaVersion: 2018
  project: "tsconfig.json"
  tsconfigRootDir: "."
  sourceType: module
  createDefaultProgram: true
env:
  es6: true
  node: true
  jest: true

extends:
  - "htmlacademy/node"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
rules:
  comma-dangle:
    - warn
    - always-multiline
  indent:
    - off
  arrow-parens:
    - error
    - as-needed
  new-cap:
    - warn
  "@typescript-eslint/no-unused-vars":
    - warn
  "@typescript-eslint/explicit-function-return-type":
    - error
  "@typescript-eslint/no-use-before-define":
    - error
    - functions: false
overrides:
  - files: "*.jsx"
    rules:
      "@typescript-eslint/explicit-function-return-type":
        - off
