extends:
  - "../../../../.eslintrc.yml"
parserOptions:
  project: "src/service/tsconfig.json"
overrides:
  - files:
      - "*.e2e.test.ts"
    rules:
      "@typescript-eslint/no-unsafe-member-access":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off
